spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.10.11:3306/demo_sxd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  redis:
    lone:
      host: 172.20.10.11
      port: 6379
#      password: root
  # database: 0
#    cluster:
#      nodes: 172.20.10.11:7001,172.20.10.11:7003,172.20.10.11:7004,172.20.10.11:7005
#      password: root


hbase:
  zookeeper:
    quorum: 172.20.10.11
    port: 2181
 #    hbase.zookeeper.znode: /hbase
 #    hbase.client.keyvalue.maxsize: 1572864000


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # sql打印到控制台
  mapper-locations: classpath:mapper/*Mapper.xml